name: update catalog every sunday

on:
  issues:
    types:
      - opened

jobs:
  build:
    name: Update the catalog.csv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOPJOR_GITHUB_TOKEN }}
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip pip install requests PyGithub pathlib GitPython pyyaml'
        
    - name: Update the catalog.csv
      env:
        SECRET: ${{ secrets.TOPJOR_GITHUB_TOKEN }}
      run: python .github/scripts/update_catalog.py
    - name: Push the Changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated catalog"
        git push -f origin master


