name: Update catalog every sunday

on:
  push:
    branches:
      - compare-the-above-two-lists-to-get-new-pecha-ids

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.9"]

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    

    - name: Import dependency 
      run : python3 -m pip install --upgrade PyGithub requests PyYAML
     
    - name: Update the catalog.csv
      env:
        SECRET: ${{secrets.GITHUB_TOKEN}}
      run: python3 catalog.py
