name: Update catalog every sunday

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    

    - name: Import dependency 
      run : python3 -m pip install --upgrade PyGithub requests PyYAML
     
    - name: Update the catalog.csv
      env:
        SECRET: ${{secrets.ACCESS_TOKEN}}
      run: python catalog.py
    
    - name: Commit changes to the checked-out repository
      run: |
        # Commit changes to the checked-out repository
        git config --global user.email "zakongjampa@gmail.com"
        git config --global user.name "Jampa Dhondup"
        git add .
        git commit -m "Update catalog.csv"

    - name: Push changes to the main repository
      
      run: |
        # Push changes to the main repository
        git push origin HEAD:main
